import { Buffer } from 'node:buffer';
import type { ArtifactKind, ProducedArtefact } from '@gorenku/core';
import type { ProviderJobContext } from './types.js';
import {
  generateSimulatedDataForMimeType,
  resolveDurationForSimulatedMedia,
} from './sdk/unified/simulated-media.js';

const blobKinds = new Set<ArtifactKind>([
  'GeneratedAudio',
  'MusicTrack',
  'GeneratedMusic',
  'GeneratedImage',
  'StartImage',
  'GeneratedVideo',
  'FinalVideo',
]);

const expectedMimeTypes: Partial<Record<ArtifactKind, string>> = {
  GeneratedAudio: 'audio/wav',
  MusicTrack: 'audio/mpeg',
  GeneratedMusic: 'audio/mpeg',
  GeneratedImage: 'image/png',
  StartImage: 'image/png',
  GeneratedVideo: 'video/mp4',
  FinalVideo: 'video/mp4',
};

export async function createSimulatedFallbackArtefacts(
  request: ProviderJobContext
): Promise<ProducedArtefact[]> {
  const extras = request.context.extras as Record<string, unknown> | undefined;
  const resolvedInputs = extras?.resolvedInputs as Record<string, unknown> | undefined;
  const jobContext = extras?.jobContext as
    | {
        inputBindings?: Record<string, string>;
      }
    | undefined;

  return Promise.all(request.produces.map(async (artefactId, index) => {
    const kind = parseArtifactKind(artefactId);
    const baseKind = kind?.split('.').pop();
    const expectedMimeType = baseKind ? expectedMimeTypes[baseKind] : undefined;
    const simulatedResponse = createSimulatedFallbackResponse({
      provider: request.provider,
      model: request.model,
      artefactId,
      kind: baseKind ?? kind,
      index,
    });
    const report = serializeReport({
      request,
      artefactId,
      kind,
      index,
      expectedMimeType,
      simulatedResponse,
    });
    const blob = await buildSimulatedFallbackBlob({
      expectedMimeType,
      durationInputId: jobContext?.inputBindings?.Duration,
      resolvedInputs,
      report,
    });

    return {
      artefactId,
      status: 'succeeded',
      blob,
      diagnostics: {
        provider: request.provider,
        model: request.model,
        expectedMimeType,
        attempt: request.attempt,
        index,
        simulatedReport: report,
      },
    };
  }));
}

function serializeReport(args: {
  request: ProviderJobContext;
  artefactId: string;
  kind?: ArtifactKind;
  index: number;
  expectedMimeType?: string;
  simulatedResponse: string;
}): string {
  const { request, artefactId, kind, index, expectedMimeType, simulatedResponse } = args;
  const metadata = {
    provider: request.provider,
    model: request.model,
    environment: request.context.environment ?? 'local',
    jobId: request.jobId,
    produces: artefactId,
    inputs: request.inputs,
    providerConfig: request.context.providerConfig,
    attachments: request.context.rawAttachments,
    extras: request.context.extras,
  };

  const attachmentSummaries = (metadata.attachments ?? []).map((attachment) => ({
    name: attachment.name,
    format: attachment.format,
    preview: attachment.contents.slice(0, 200),
  }));

  const lines = [
    '# Simulated Provider Invocation',
    '',
    `Provider: ${metadata.provider}`,
    `Model: ${metadata.model}`,
    `Environment: ${metadata.environment}`,
    `Job ID: ${metadata.jobId}`,
    `Artefact: ${metadata.produces}`,
    `Attempt: ${request.attempt}`,
    `Invocation Index: ${index}`,
    kind ? `Artifact Kind: ${kind}` : 'Artifact Kind: unknown',
    expectedMimeType
      ? isMediaMimeType(expectedMimeType)
        ? `Expected Output Mime Type: ${expectedMimeType} (valid simulated media emitted)`
        : `Expected Output Mime Type: ${expectedMimeType}`
      : 'Expected Output Mime Type: text/plain',
    '',
    'Inputs:',
    formatList(metadata.inputs),
    '',
    'Provider Config:',
    formatValue(metadata.providerConfig),
    '',
    'Attachments:',
    formatAttachments(metadata.attachments ?? []),
    '',
    'Extras:',
    formatValue(metadata.extras),
    '',
    'Attachment Summaries:',
    formatValue(attachmentSummaries),
    '',
    'Simulated Response:',
    indent(simulatedResponse),
    '',
    'Note: This artefact was generated by the simulated fallback handler. No external API was called.',
  ];

  return formatSection(lines);
}

function createSimulatedFallbackResponse(args: {
  provider: string;
  model: string;
  artefactId: string;
  kind?: ArtifactKind;
  index: number;
}): string {
  const { provider, model, artefactId, kind, index } = args;
  const base = `${provider}/${model}`;
  if (!kind || !blobKinds.has(kind)) {
    return `Simulated response for ${artefactId} (#${index + 1}) generated by ${base}.`;
  }

  return [
    `Simulated fallback artefact placeholder for ${artefactId} (#${index + 1}).`,
    `Original output kind: ${kind}.`,
    `Provider: ${base}.`,
    'A valid simulated media payload was generated by the generic simulated fallback.',
  ].join(' ');
}

async function buildSimulatedFallbackBlob(args: {
  expectedMimeType?: string;
  durationInputId?: string;
  resolvedInputs: Record<string, unknown> | undefined;
  report: string;
}): Promise<{ data: Buffer; mimeType: string }> {
  const { expectedMimeType, durationInputId, resolvedInputs, report } = args;
  if (!expectedMimeType || !isMediaMimeType(expectedMimeType)) {
    return {
      data: Buffer.from(report, 'utf8'),
      mimeType: expectedMimeType ?? 'text/plain',
    };
  }

  const durationSeconds = expectedMimeType.startsWith('image/')
    ? 0
    : resolveDurationForSimulatedMedia({
        durationInputId,
        resolvedInputs,
      });

  return {
    data: await generateSimulatedDataForMimeType({
      mimeType: expectedMimeType,
      durationSeconds,
    }),
    mimeType: expectedMimeType,
  };
}

function parseArtifactKind(artefactId: string): ArtifactKind | undefined {
  const match = /^Artifact:([^[]+)/.exec(artefactId);
  if (!match) {
    return undefined;
  }
  return match[1] as ArtifactKind;
}

function isMediaMimeType(mimeType: string): boolean {
  return (
    mimeType.startsWith('image/') ||
    mimeType.startsWith('video/') ||
    mimeType.startsWith('audio/')
  );
}

function formatSection(lines: string[]): string {
  return lines.join('\n').trimEnd() + '\n';
}

function formatList(items: string[]): string {
  if (!items || items.length === 0) {
    return '  (none)';
  }
  return items.map((item) => `  - ${item}`).join('\n');
}

function formatAttachments(attachments: ProviderJobContext['context']['rawAttachments']): string {
  if (!attachments || attachments.length === 0) {
    return '  (none)';
  }
  const lines: string[] = [];
  for (const attachment of attachments) {
    lines.push(`  - ${attachment.name} (${attachment.format})`);
    lines.push(indent(truncate(attachment.contents, 800)));
  }
  return lines.join('\n');
}

function formatValue(value: unknown): string {
  if (value === undefined) {
    return '  (none)';
  }
  if (typeof value === 'string') {
    if (value.trim().length === 0) {
      return '  (empty string)';
    }
    return indent(truncate(value, 800));
  }
  try {
    const json = JSON.stringify(value, null, 2);
    return json ? indent(truncate(json, 2000)) : '  (none)';
  } catch {
    return '  (unserializable value)';
  }
}

function indent(value: string, spaces = 2): string {
  const padding = ' '.repeat(spaces);
  return value
    .split('\n')
    .map((line) => `${padding}${line}`)
    .join('\n');
}

function truncate(value: string, limit: number): string {
  if (value.length <= limit) {
    return value;
  }
  const remaining = value.length - limit;
  return `${value.slice(0, limit)}... (truncated ${remaining} chars)`;
}
